---
- name: Install MongoDB
  hosts: gcpservers
  become: yes
  become_method: sudo
  tasks:
  - name: Update packages
    apt:
        name: "*"
        state: latest
  - name: Upgrade packages
    apt:
        upgrade: dist
  - name: Install MongoDB package
    apt:
        name: mongodb
        state: latest
        update_cache: yes
  - name: Start MongoDB service
    systemd:
        name: mongodb
        state: started

- name: Install React App
  hosts: gcpservers
  become: yes
  become_method: sudo
  tasks:
  - name: Copy react files
    copy:
        src: ~/bursaryproject/React
        dest: ~/bursaryproject/React

  - name: Install node
    apt:
        name: nodejs-legacy
        state: latest

  - name: Install npm
    apt:
        name: npm
        state: latest
