---
- name: Install MongoDB
  hosts: gcpservers
  become: yes
  become_method: sudo
  tasks:
  - name: Update packages
    apt:
        name: "*"
        state: latest
  - name: Upgrade packages
    apt:
        upgrade: dist
  - name: Install MongoDB package
    apt:
        name: mongodb
        state: latest
        update_cache: yes
  - name: Start MongoDB service
    systemd:
        name: mongodb
        state: started
