 - name: Ensure nginx, npm and nodejs are installed.
   apt:
       name: "{{ react_dependencies }}"
       state: latest
       update_cache: yes

 - name: Send React files to remote server.
   copy:
       directory_mode: yes
       src: "{{ react_src }}"
       dest: "{{ react_dest }}"
       owner: "{{ react_user }}"
       group: "{{ react_user }}"
       mode: "{{ access_mode }}"

 - name: Edit .env file with correct external IP.
   lineinfile:  
       path: "{{ react_dest }}/.env"
       regexp: '^(.*)REACT_APP_AWS_IP=localhost(.*)$'
       line: "REACT_APP_AWS_IP={{ external_ip }}"
 
 - name: Correct access permissions on copied files.
   file:
        path: "{{ react_dest }}"
        mode: "{{ access_mode }}"
        owner: "{{ react_user }}"
        group: "{{ react_user }}"
        state: directory
        recurse: yes
 
 - name: Install npm dependencies
   shell: npm install
   args:
      chdir: "{{ react_dest }}"

 - name: Build static react application.
   shell: npm run-script build
   args:
       chdir: "{{ react_dest }}"

 - name: Start nginx service.
   systemd:
       daemon_reload: yes
       name: nginx
       state: started

 - name: Ensure nginx is running.
   service:
       name: nginx
       state: started

 - name: Add nginx config file.
   copy:
       force: yes
       src:  "{{ nginx_src }}"
       dest: "{{ nginx_dest }}"
 
 - name: Reload nginx service.
   shell: nginx -s reload
