access_mode: '751'
nginx_src: files/nginx.conf
nginx_dest: /etc/nginx/nginx.conf
react_src: files/bursaryproject/React/
react_dest: /tmp/ReactApp
react_user: lukeajones1996
react_dependencies:
        - npm
        - nginx
        - nodejs
